<?php

declare(strict_types=1);

use TempestPico\ExampleComponents\GitHubRepos;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var GitHubRepos $this
 */
echo $this->toHtml();
