<?php

declare(strict_types=1);

use TempestPico\ExampleComponents\HelloWorld;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var HelloWorld $this
 */
echo $this->toHtml();
