<?php

declare(strict_types=1);

use TempestPico\ExampleComponents\ListHtmlView;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var ListHtmlView $this
 */
echo $this->toHtml();
