<?php

declare(strict_types=1);

use TempestPico\ExampleComponents\MixedView2;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var MixedView2 $this
 */
echo $this->toHtml();
