<?php

declare(strict_types=1);

use TempestPico\ExampleComponents\MixedView3;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var MixedView3 $this
 */
echo $this->toHtml();
