<?php

declare(strict_types=1);

namespace AKl\Tempest_HtmlView;

use Dom\HTMLDocument;
use Tempest\Log\Logger;
use Tempest\Support\Html\HtmlString;
use Tempest\Support\Path\Path;
use Tempest\View\View;
use AKl\Tempest_HtmlView\AssetManager;
use AKl\Tempest_HtmlView\Exception\DomManipulationFailed;

use function Tempest\get;
use function Tempest\Support\Arr\is_empty;
use function Tempest\Support\Arr\sort_keys;
use function Tempest\Support\Filesystem\write_file;
use function Tempest\Support\path;

abstract class HtmlView implements View
{
    private readonly Path $basePath;
    private readonly string $baseName;

    private string $viewDir = 'HtmlViews' . \DIRECTORY_SEPARATOR; // TODO: make this configurable

    public string $path {
        get => $this->viewDir . $this->baseName . '.view.php';
    }

    public string $relativeRootPath {
        // or relative to *.view.php?
        get => $this->basePath->toString();
    }

    /** @var array<int, \Closure(HTMLDocument):HTMLDocument> */
    private(set) array $DomManipulations = [];

    public function __construct()
    {
        $this->setPaths();
        $this->createViewFile($this->basePath->append(DIRECTORY_SEPARATOR, $this->path));
        $this->autoUseAssets();
    }

    abstract public function template(): HtmlContent;

    public function toHtml(): HtmlString
    {
        if (is_empty($this->DomManipulations)) {
            return $this->template()->render();
        }

        $dom = Dom(
            $this->template()->render()->toString(),
        );

        foreach (sort_keys($this->DomManipulations) as $manipulation) {
            try {
                $dom = $manipulation($dom);
            } catch (\Throwable $th) {
                throw new DomManipulationFailed(
                    $th,
                    onFile: $this->path,
                    manipulator: $manipulation,
                );
            }
        }

        return new HtmlString($dom->body->innerHTML ?? '');
    }

    /**
     * Convert the rendered HTML of the component to a \Dom\HTMLDocument.
     *
     * TODO: test it…
     * /
    public function toDomFragment(): HTMLDocument
    {
        return HTMLDocument::createFromString($this->toHtml()->toString());
    }
*/
    /**
     * Manipulate (or just inspect/cache) the DOM after the full VT of THIS view (including the content) is rendered.
     * Useful for experiments and third party components.
     * The manipulator receives and must return a Dom\HTMLDocument.
     *
     * NOTE: Unfortunately, we can't use modern arrow functions or fluent syntax for the manipulator,
     * because most Dom\HTMLDocument's methods rather return `void` instead the document itself.
     *
     * The condition parameter can be used to add the manipulation only if a certain condition is met.
     *
     * @param int<0, 10> $executionOrder (default: 5)
     * Manipulations with the same `$executionOrder` will be executed in the order they were added.
     * Use 3 for earlier, 7 for later and 1/9 for very early/late and so on.
     *
     * @example
     * ```php
     *    $body->onRender(
     *       manipulator: static function (HTMLDocument $dom) {
     *           each(
     *               $dom->querySelectorAll('div')->getIterator(),
     *               static function ($node) {
     *                   $node->classList->add('outline');
     *               },
     *           );
     *          return $dom;
     *       },
     *       condition: env('ENVIRONMENT') === 'local'
     *    );
     * ```
     *
     * @param \Closure(HTMLDocument):HTMLDocument $manipulator
     */
    public function onRender(
        \Closure $manipulator,
        bool $condition = true,
        int $executionOrder = 5,
    ): static {
        if (! $condition) {
            return $this;
        }

        $this->DomManipulations[
            ($executionOrder * 100) + count($this->DomManipulations)
        ] = $manipulator;

        return $this;
    }

    public function createViewFile(Path $viewPath): bool
    {
        if ($viewPath->exists()) {
            return false;
        }

        $className = static::class;
        $self = self::class;

        write_file(
            $viewPath->toString(),
            <<<PHP
                <?php

                declare(strict_types=1);

                /**
                 * This HtmlView was automatically generated by {$self}.
                 * @var {$className} \$this
                 */
                echo \$this->toHtml();
                PHP,
        );

        $logger = get(Logger::class);
        $logger->notice('Created view file.', context: [
            'for' => static::class,
            'at' => $viewPath->toString(),
        ]);

        return true;
    }

    private function setPaths(): void
    {
        $file = new \ReflectionClass($this)->getFileName();

        if ($file === false) {
            throw new \LogicException(
                'Unable to determine the file path of the component.',
            );
        }

        $path = path($file);

        // @mago-expect analysis:invalid-property-write
        $this->basePath = $path->dirname();
        // @mago-expect analysis:invalid-property-write
        $this->baseName = $path->filename()->stripEnd('.php')->toString();
    }

    private function autoUseAssets(): void
    {
        $cssFile = $this->basePath->append(
            \DIRECTORY_SEPARATOR,
            $this->baseName,
            '.css',
        );

        if ($cssFile->exists()) {
            // @mago-expect analysis:possibly-invalid-argument
            get(AssetManager::class)->css(
                $cssFile->toString(),
                isRealPath: \true,
            );
        }

        // TODO: JS
    }

    // ### required by tempest ###

    /** @var mixed[] $data */
    public array $data = [];

    public function get(string $key): mixed
    {
        // @mago-expect analysis:string-member-selector
        return $this->{$key} ?? $this->data[$key] ?? null;
    }

    public function has(string $key): bool
    {
        return array_key_exists($key, $this->data) || property_exists($this, $key);
    }

    public function data(mixed ...$params): static // self
    {
        $this->data = [...$this->data, ...$params];

        return $this;
    }
}
