<?php

declare(strict_types=1);

namespace TempestPico\Page;

use Tempest\Reflection\ClassReflector;
use Tempest\Router\Get;
use Tempest\Router\Prefix;
use Tempest\Router\StaticPage;
use Tempest\Support\Path\Path;
use TempestPico\Components\Accordion;
use TempestPico\Components\Card;
use TempestPico\Components\CodeBlock;
use TempestPico\Components\Component;
use TempestPico\Components\Doc;
use TempestPico\Components\InlineMarkdown;
use TempestPico\Components\Markdown;
use TempestPico\Components\Messages;
use TempestPico\Components\Stack;
use TempestPico\Layout\Page;
use TempestPico\Support\Html\HtmlViewTree;

use function Tempest\reflect;
use function Tempest\Support\arr;
use function Tempest\Support\Arr\implode;
use function Tempest\Support\Filesystem\read_file;
use function Tempest\Support\path;
use function Tempest\Support\Str\class_basename;
use function TempestPico\Support\Html\Html;
use function TempestPico\Support\Html\MD;
use function TempestPico\Support\Html\VT;

#[Prefix('/doc')]
final readonly class Docs
{
    #[StaticPage]
    #[Get('/')]
    public function __invoke(): Page
    {
        return new Page(
            title: 'Documentation',
            isStatic: true,
            main: new Stack(
                new Card(
                    content: new Markdown(
                        'Tempest-Pico is still a work in progress, but I will try to keep it up to date.',
                    ),
                ),
                new Markdown(<<<'MD'
                    ## Why?

                    Goal of this Project is to create a Base to quickly build *mostly* static websites,
                     used by a very small community. It is built on top of Tempest v2 (I still need PHP 8.4).

                     My own "modern PHP" Framework was written in PHP5 and ported 2015 to [Hack](https://hacklang.org/), 
                    but Hack is dead and I need to switch back to PHP again.
                    Around 10 Years I only use PHP for small scripts and to fix WordPress sites, so I'm a bit rusty and not really up to date with modern PHP Tools.
                    So fell free to give me feedback like "Hey, you should use this library." or "This is not how you should do it, you should do it like this!".

                    In the long run, I like to replace some WordPress sites with Tempest.
                    Unfortunately, Tempest own View system is not really suitable for me, thats why I created my own "**HTML View Tree Builder**" on top of it. It is not battle-tested, but it solved some Issus I had. I'm happy with it so far.

                    Take a look at the [Components](doc/components) code to see how I use it, maybe it is also useful for you.

                    MD),
                new Markdown('-------'),
                new Markdown('Well, the next is (mostly) generated by Copilot for itself… But why not use it?'),
                new Markdown(read_file(__DIR__ . '/../../.github/copilot-instructions.md')),
            ),
        );
    }

    #[StaticPage]
    #[Get('/readme')]
    public function readme(): Page
    {
        return new Page(
            title: 'README.md:',
            isStatic: true,
            main: new Stack(
                new Markdown(read_file(__DIR__ . '/../../README.md')),
            ),
        );
    }

    #[StaticPage]
    #[Get('/components')]
    public function components(): Page
    {
        $cards = arr(Doc::COMPONENTS)
            ->sort()
            ->map(
                function ($component) {
                    /** @var ClassReflector<Component> */
                    $ref = reflect($component);
                    $file = $ref->getFileName();
                    $exampleFile = path($file)
                        ->dirname()
                        ->append(DIRECTORY_SEPARATOR)
                        ->append('Examples')
                        ->append(DIRECTORY_SEPARATOR)
                        ->append(basename($file));

                    $docFile = $exampleFile->replaceEnd('.php', '.md');

                    $content = VT();

                    if ($docFile->exists()) {
                        $content->appendContent(
                            MD(read_file($docFile->toString())),
                        );
                    }

                    if ($exampleFile->exists()) {
                        $output = $this->runExample($exampleFile);
                        $exampleCode = read_file($exampleFile->toString());

                        $content->appendContent(new Accordion(
                            class_basename($component),
                            [
                                '*Live* Example' => $output,
                                'Example Code' => new CodeBlock(
                                    $exampleCode,
                                    'php',
                                ),
                                'HTML Output' => new CodeBlock(
                                    $output->render()->toString(),
                                    'html',
                                ),
                            ],
                            Accordion::Options('h3'),
                        ));
                    } else {
                        $content->appendContent(new Messages(
                            ['variant' => 'info', 'md' => 'Sorry, there is no Example'],
                        ));
                    }

                    $content->appendContent(
                        new Accordion(
                            class_basename($component),
                            [
                                'Code: ' . path($file)->basename()->toString() => new CodeBlock(
                                    path($file),
                                    'php',
                                ),
                            ],
                            Accordion::Options('h3'),
                        ),
                    );

                    return $this->asCard($ref, $content);
                },
            );

        return new Page(
            title: 'Components Overview',
            isStatic: true,
            main: new Stack(new Markdown('A List of the components I have created so far.'), ...$cards),
        );
    }

    /** @param ClassReflector<Component> $ref */
    private function asCard(ClassReflector $ref, HtmlViewTree $content): Component
    {
        $doc = $ref->getAttribute(Doc::class);

        return new Card(
            header: VT(
                Html('h2', [$ref->getShortName()]),
                new Markdown(is_null($doc) ? 'No description available.' : $doc->description),
            ),
            content: $content,

            footer: is_null($doc) ? null : $this->hashTags($doc->tags),
        );
    }

    /** @param null|string|string[] $tags */
    private function hashTags(null|string|array $tags): ?Component
    {
        return is_null($tags)
            ? null
            : new InlineMarkdown("\n\n #" . (is_string($tags) ? $tags : implode($tags, ' #')));
    }

    /**  safely??? run the example code */
    private function runExample(Path $exampleFile): HtmlViewTree
    {
        try {
            return include $exampleFile;
        } catch (\Throwable $th) {
            throw new \Exception('Error in Example', 1, $th);
        }
    }
}
