<?php

declare(strict_types=1);

namespace TempestPico\Page;

use AKl\Tempest_HtmlView\AssetManager;
use Dom\Element;
use Dom\HTMLDocument;
use Tempest\Router\Get;
use Tempest\Router\Prefix;
use Tempest\Router\StaticPage;
use TempestPico\Components\Accordion;
use TempestPico\Components\BurgerMenu;
use TempestPico\Components\Card;
use TempestPico\Components\CodeBlock;
use TempestPico\Components\ComponentDocumentation;
use TempestPico\Components\Input;
use TempestPico\Components\LinkList;
use TempestPico\Components\MainNav;
use TempestPico\Components\Markdown;
use TempestPico\Components\Message;
use TempestPico\Components\Modal;
use TempestPico\Components\PhpDom;
use TempestPico\Components\Table;
use TempestPico\Components\Typewriter;
use TempestPico\ExampleComponents\HelloWorld;
use TempestPico\ExampleComponents\ListHtmlView;
use TempestPico\ExampleComponents\ListView;
use TempestPico\ExampleComponents\MixedView;
use TempestPico\ExampleComponents\MixedView2;
use TempestPico\ExampleComponents\MixedView3;
use TempestPico\Layout\Page;

use function AKl\Tempest_HtmlView\content;
use function AKl\Tempest_HtmlView\Html;
use function AKl\Tempest_HtmlView\MD;
use function Tempest\get;
use function Tempest\Support\Arr\each;
use function Tempest\Support\Arr\map_iterable;
use function Tempest\Support\path;

#[Prefix('/doc')]
final readonly class Documentation
{
    #[StaticPage]
    #[Get('/')]
    public function __invoke(): Page
    {
        return new Page(
            title: 'Documentation',
            meta: [
                'description' => 'Documentation for Tempest-HtmlView',
            ],
            main: content(
                new Message(
                    variant: 'warning',
                    md: 'Tempest-Pico is still a work in progress and
                    built on top of Tempest **v2** (I still need *PHP 8.4*). \
                    \
                    Right now I use Yohns PicoCSS fork, but I would like to replace it with components that have almost no styling
                    (headless) plus an extra CSS layer. That way, you can switch to your own CSS stack,
                    ~~ACSS~~ ~~Bootstrap~~ ~~Tailwind~~ ~~MaterializeCSS~~ ~~UnoCSS~~ daisyUI,
                    or whatever framework is currently popular. \
                    \
                    But maybe I will move to full-stack TypeScript before it is done. I will still upgrade to Tempest v3 for sure.',
                    impotent: true,
                ),
                new Typewriter(
                    'Tempest-HtmlView & AssetManager Doc + Components',
                    before: 'Tempest-Pico: ',
                    color: 'light-dark(green, blue)',
                ),

                MD(path(__DIR__, 'doc-overview.md')),
                Html('hr'),
                Html('h2', '.github/copilot-instructions.md'),
                new Message(
                    'info',
                    'This is mostly generated by Copilot for itself… But why not use it?',
                ),
                MD(
                    path(
                        __DIR__,
                        '/../../',
                        '.github/copilot-instructions.md', // TODO: rootDir?
                    ),
                ),
            ),
        );
    }

    #[StaticPage]
    #[Get('/components')]
    public function components(): Page
    {
        $docs = map_iterable(
            [
                BurgerMenu::class,
                CodeBlock::class,
                Input::class,
                LinkList::class,
                MainNav::class,
                Markdown::class,
                Message::class,
                Modal::class,
                PhpDom::class,
                Table::class,
                Typewriter::class,
            ],
            static fn (
                string $component,
            ): ComponentDocumentation => new ComponentDocumentation($component),
        );

        return new Page(
            title: 'Components Overview',
            meta: [
                'description' => 'Components for Tempest-HtmlView',
            ],
            main: content(
                MD('Some of the components I have created so far.'),
                ...$docs,
            ),
        );
    }

    #[StaticPage]
    #[Get('/examples')]
    public function examples(): Page
    {
        $docs = map_iterable(
            [
                HelloWorld::class,
                ListView::class,
                ListHtmlView::class,
                MixedView::class,
                MixedView2::class,
                MixedView3::class,
                Markdown::class,
                PhpDom::class,
                // GitHubRepos::class,
                //                self::class,
            ],
            static fn (
                string $component,
            ): ComponentDocumentation => new ComponentDocumentation($component),
        );

        $docs[] = new Card(
            new Accordion(
                self::class,
                content: [
                    self::class => new CodeBlock(path(__FILE__), 'php'),
                ],
            ),
        );

        return new Page(
            title: 'HtmlView and HtmlContent Examples',
            meta: [
                'description' => 'Examples for Tempest-HtmlView',
            ],
            main: content(
                MD('TBD…'), // TODO: <=
                ...$docs,
            ),
        );
    }

    #[StaticPage]
    #[Get('/readme')]
    public function readme(): Page
    {
        return new Page(
            title: 'README.md:',
            main: MD(path(__DIR__, '/../../', 'README.md')), // TODO: rootDir?
        );
    }

    #[StaticPage]
    #[Get('/dom')]
    public function dom(): Page
    {
        return new Page(
            title: "PHP's Dom\HTMLDocument",
            main: content(
                MD(
                    <<<'MD'
                        If you migrate your code to Tempest, there is no need to fully rewrite your components.

                        `content()` accepts PHP 8.4's [Dom\HTMLDocument](https://www.php.net/manual/en/class.dom-htmldocument.php).

                        The `Dom()` Helper function returns such HTMLDocument and accepts a string or a file `path`.
                        The HtmlView `onRender()` method will help you manipulating its output,
                        if you can't or do not want to modify the component itself.
                        Use the `PhpDom()` Component if you need both.

                        Here is a Example:
                        MD,
                ),
                Html('hr'),
                new PhpDom(path(__DIR__, '/Modal.html')) // We need onRender, so we use the Component
                    ->onRender(static function (
                        HTMLDocument $htmlDocument,
                    ): HTMLDocument {
                        // Fix: PicoCss sets dialog to fill the screen => no space to click outside
                        each(
                            $htmlDocument
                                ->querySelectorAll('dialog')
                                ->getIterator(),
                            static function (Element $element): void {
                                $element->setAttribute(
                                    'style',
                                    'width: fit-content; height: fit-content; min-width: initial; min-height: initial;',
                                );
                            },
                        );
                        return $htmlDocument;
                    })
                    ->onRender(static function (
                        HTMLDocument $htmlDocument,
                    ): HTMLDocument {
                        // Fix: remove margin from article
                        each(
                            $htmlDocument
                                ->querySelectorAll('article')
                                ->getIterator(),
                            static function (Element $element): void {
                                $element->setAttribute('style', 'margin: 0;');
                            },
                        );
                        return $htmlDocument;
                    }),
                Html('hr'),
                MD(
                    <<<'MD'
                        A *HtmlView*s can manipulate (or just inspect) the DOM after the HTML is generated.

                        This is useful while migrating, for experiments and on third party components.

                        NOTE: Unfortunately, we cannot use modern arrow functions or fluent syntax for the manipulator,
                        because most Dom\HTMLDocument methods return `void` instead of the document itself.

                        The condition parameter can be used to add the manipulation only if a certain condition is met.
                        MD,
                ),
                new CodeBlock(
                    <<<'Code'
                        $component // a HtmlView
                            // While local developing add the class `outline` on each `<div>`
                            ->onRender(
                                static function (HTMLDocument $dom) {
                                    each(
                                        $dom->querySelectorAll('div')->getIterator(),
                                        static function (\Dom\Element $node) {
                                            $node->classList->add('outline');
                                        },
                                    );
                                    return $dom;
                                },
                                condition: env('ENVIRONMENT') === 'local'
                            );
                        Code,
                    'php',
                ),
            ),
        );
    }

    #[StaticPage]
    #[Get('/asset_manager')]
    public function assetManager(): Page
    {
        $assets = get(AssetManager::class);
        // Load legacy Typewriter JS (not versioned)
        $assets->requireScript(
            'https://unpkg.com/typewriter-effect@latest/dist/core.js',
        );
        // implementation as versioned asset
        $assets->use('ExampleComponents/OldTypewriter.js');

        return new Page(
            title: 'AssetManager',
            main: content(
                'TBD…',
                MD(
                    <<<'MD'
                        Given you have an HtmlView called `Example.php`,
                        `Example.css` is automatically versioned and included.

                        TODO: same for *.js and *.mjs.

                        Here we have a legacy JavaScript example (I now use pure CSS instead).
                        MD,
                ),
                new CodeBlock(
                    <<<'Code'

                        $assets = get(AssetManager::class);
                        // Load legacy Typewriter JS (not versioned)
                        $assets->requireScript(
                            'https://unpkg.com/typewriter-effect@latest/dist/core.js',
                        );
                        // versioned, Path relative to configured srcRoot
                        $assets->use('ExampleComponents/OldTypewriter.js');

                        Html('div', attributes: ['id' => 'Typewriter']),
                        Code,
                    'php',
                ),
                Html('div', attributes: ['id' => 'Typewriter']),
            ),
        );
    }
}
