<?php

declare(strict_types=1);

use TempestPico\Components\Accordion;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var Accordion $this
 */
echo $this->toHtml();
