<?php

declare(strict_types=1);

use TempestPico\Components\BurgerMenu;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var BurgerMenu $this
 */
echo $this->toHtml();
