<?php

declare(strict_types=1);

use TempestPico\Components\CodeBlock;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var CodeBlock $this
 */
echo $this->toHtml();
