<?php

declare(strict_types=1);

use TempestPico\Components\ComponentDocumentation;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var ComponentDocumentation $this
 */
echo $this->toHtml();
