<?php

declare(strict_types=1);

use TempestPico\Components\InlineMarkdown;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var InlineMarkdown $this
 */
echo $this->toHtml();
