<?php

declare(strict_types=1);

use TempestPico\Components\LinkList;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var LinkList $this
 */
echo $this->toHtml();
