<?php

declare(strict_types=1);

use TempestPico\Components\MainNav;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var MainNav $this
 */
echo $this->toHtml();
