<?php

declare(strict_types=1);

use TempestPico\Components\Markdown;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var Markdown $this
 */
echo $this->toHtml();
