<?php

declare(strict_types=1);

use TempestPico\Components\Message;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var Message $this
 */
echo $this->toHtml();
