<?php

declare(strict_types=1);

use TempestPico\Components\Typewriter;

/**
 * This HtmlView was automatically generated by AKl\Tempest_HtmlView\HtmlView.
 * @var Typewriter $this
 */
echo $this->toHtml();
